# Generated by Django 3.2.16 on 2023-03-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_device_lifecycle_mgmt', '0009_software_remove_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesoftwarevalidationresult',
            name='valid_software',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
