# Generated by Django 3.2.16 on 2023-03-16 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_device_lifecycle_mgmt', '0010_devicesoftwarevalidationresult_valid_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesoftwarevalidationresult',
            name='valid_software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nautobot_device_lifecycle_mgmt.validatedsoftwarelcm'),
        ),
    ]
