# Generated by Django 3.2.16 on 2023-03-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_device_lifecycle_mgmt', '0015_alter_devicesoftwarevalidationresult_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemsoftwarevalidationresult',
            name='valid_software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nautobot_device_lifecycle_mgmt.validatedsoftwarelcm'),
        ),
    ]
