# Generated by Django 3.2.16 on 2023-04-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_device_lifecycle_mgmt', '0017_auto_20230403_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesoftwarevalidationresult',
            name='valid_software',
            field=models.ManyToManyField(to='nautobot_device_lifecycle_mgmt.ValidatedSoftwareLCM'),
        ),
    ]
