# Generated by Django 3.2.16 on 2023-04-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_device_lifecycle_mgmt', '0019_alter_devicesoftwarevalidationresult_valid_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesoftwarevalidationresult',
            name='valid_software',
            field=models.ManyToManyField(related_name='_nautobot_device_lifecycle_mgmt_devicesoftwarevalidationresult_valid_software_+', to='nautobot_device_lifecycle_mgmt.ValidatedSoftwareLCM'),
        ),
    ]
