# Generated by Django 3.2.16 on 2023-04-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_device_lifecycle_mgmt', '0021_auto_20230404_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesoftwarevalidationresult',
            name='valid_software',
            field=models.ManyToManyField(related_name='_validatedsoftwarelcm', to='nautobot_device_lifecycle_mgmt.ValidatedSoftwareLCM'),
        ),
    ]
